name: base
description: Base SDRF template with shared columns inherited by all proteomics templates. This is a construction artifact and cannot be used directly - use ms-proteomics or affinity-proteomics instead.
version: 1.1.0
usable_alone: false
validators:
  - validator_name: trailing_whitespace_validator
    params: {}
  - validator_name: column_order
    params: {}
  - validator_name: empty_cells
    params: {}
  - validator_name: combination_of_columns_no_duplicate_validator
    params:
      column_name:
        - source name
        - assay name
      column_name_warning:
        - source name
        - assay name
columns:
  - name: source name
    description: Unique identifier for the biological sample
    requirement: required
    allow_not_applicable: false
    allow_not_available: false

  - name: characteristics[organism]
    description: Species of the sample using NCBI Taxonomy
    requirement: required
    allow_not_applicable: true
    allow_not_available: false
    validators:
      - validator_name: ontology
        params:
          ontologies:
            - ncbitaxon
          error_level: error
          description: The organism should be a valid NCBI Taxonomy term
          examples:
            - homo sapiens
            - mus musculus
            - rattus norvegicus
            - saccharomyces cerevisiae

  - name: characteristics[organism part]
    description: Anatomical part of the organism from which sample was derived
    requirement: required
    cardinality: multiple
    allow_not_applicable: true
    allow_not_available: true
    validators:
      - validator_name: ontology
        params:
          ontologies:
            - uberon
            - bto
          error_level: warning
          description: The organism part should be a valid UBERON or BTO term
          examples:
            - liver
            - brain
            - heart
            - blood

  - name: characteristics[cell type]
    description: Cell type of the sample
    requirement: recommended
    cardinality: multiple
    allow_not_applicable: true
    allow_not_available: true
    validators:
      - validator_name: ontology
        params:
          ontologies:
            - cl
            - bto
            - clo
          error_level: warning
          description: The cell type should be a valid Cell Ontology (CL), BRENDA Tissue Ontology (BTO), or Cell Line Ontology (CLO) term
          examples:
            - hepatocyte
            - neuron
            - fibroblast
            - T cell

  - name: characteristics[biological replicate]
    description: Identifier for the biological replicate (integer starting from 1, or 'pooled' for pooled samples)
    requirement: required
    allow_not_applicable: false
    allow_not_available: false
    allow_pooled: true
    validators:
      - validator_name: pattern
        params:
          pattern: ^\d+$|^pooled$
          description: Biological replicate should be an integer or 'pooled' for pooled reference samples
          examples:
            - 1
            - 2
            - pooled

  - name: assay name
    description: Unique identifier for the data acquisition run
    requirement: required
    allow_not_applicable: false
    allow_not_available: false

  - name: technology type
    description: Type of technology used
    requirement: required
    allow_not_applicable: false
    allow_not_available: false
    validators:
      - validator_name: single_cardinality_validator
        params: {}
      - validator_name: values
        params:
          values:
            - proteomic profiling by mass spectrometry
            - protein expression profiling by antibody array
            - protein expression profiling by aptamer array

  - name: comment[instrument]
    description: Instrument used for data acquisition (MS instrument or affinity platform)
    requirement: required
    cardinality: multiple
    allow_not_applicable: false
    allow_not_available: false
    validators:
      - validator_name: ontology
        params:
          ontologies:
            - ms
            - pride
          error_level: warning
          description: The instrument should be a valid MS or PRIDE ontology term

  - name: comment[technical replicate]
    description: Identifier for the technical replicate (integer starting from 1)
    requirement: recommended
    type: integer
    allow_not_applicable: false
    allow_not_available: false

  - name: comment[data file]
    description: Name of the raw data file
    requirement: required
    allow_not_applicable: false
    allow_not_available: false

  - name: comment[sdrf version]
    description: Version of the SDRF-Proteomics specification used to annotate this file
    requirement: recommended
    allow_not_applicable: false
    allow_not_available: false
    validators:
      - validator_name: pattern
        params:
          pattern: ^v\d+\.\d+\.\d+(-[\w.]+)?$
          description: SDRF version should follow semantic versioning format (e.g., v1.1.0)
          examples:
            - v1.1.0
            - v1.0.0
            - v2.0.0-dev

  - name: comment[sdrf template]
    description: Template name and version used for annotation. Two formats are supported - key=value format (NT=template_name;version=vX.Y.Z) or simple format (template_name vX.Y.Z). Multiple templates can be specified using multiple columns.
    requirement: optional
    cardinality: multiple
    allow_not_applicable: false
    allow_not_available: false
    validators:
      - validator_name: pattern
        params:
          pattern: ^(NT=[\w-]+;version=v\d+\.\d+\.\d+(-[\w.]+)?|[\w-]+ v\d+\.\d+\.\d+(-[\w.]+)?)$
          description: Template can be specified as 'NT=name;version=vX.Y.Z' or 'name vX.Y.Z'
          examples:
            - NT=human;version=v1.1.0
            - human v1.1.0
            - NT=ms-proteomics;version=v1.1.0
            - ms-proteomics v1.1.0

  - name: comment[sdrf annotation tool]
    description: Software tool or method used to generate or annotate the SDRF file. Two formats are supported - key=value format (NT=tool_name;version=vX.Y.Z) or simple format (tool_name vX.Y.Z).
    requirement: optional
    allow_not_applicable: false
    allow_not_available: false
    validators:
      - validator_name: pattern
        params:
          pattern: ^(NT=[\w-]+;version=v[\d.]+[\w.-]*|[\w-]+ v[\d.]+[\w.-]*|manual curation)$
          description: Annotation tool can be specified as 'NT=name;version=vX.Y.Z' or 'name vX.Y.Z' or 'manual curation'
          examples:
            - NT=lesSDRF;version=v0.1.0
            - lesSDRF v0.1.0
            - NT=sdrf-pipelines;version=v1.0.0
            - sdrf-pipelines v1.0.0
            - manual curation

  - name: comment[modification parameters]
    description: Post-translational modifications searched
    requirement: recommended
    cardinality: multiple
    allow_not_applicable: true
    allow_not_available: true
    validators:
      - validator_name: ontology
        params:
          ontologies:
            - unimod
          error_level: warning
          description: The modification parameters should be valid Unimod terms
          examples:
            - NT=Oxidation;MT=Variable;TA=M;AC=Unimod:35
            - NT=Carbamidomethyl;TA=C;MT=fixed;AC=UNIMOD:4
